# default setting
monitor=,preferred,auto,auto

# import my own settings
source = ~/.config/hypr/my_hypr.conf  # general settings, looks&feel
source = ~/.config/hypr/monitors_only_laptop.conf  # monitor settings

